In [29]:
import boto3
import pandas as pd

AWS_PROD_ACCESS_KEY = "AKIAV3CMPTUBHDFPVWGR"
AWS_PROD_SECRET_ACCESS_KEY = "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"


s3_client=boto3.client(
    's3',
    aws_access_key_id=AWS_PROD_ACCESS_KEY,
    aws_secret_access_key=AWS_PROD_SECRET_ACCESS_KEY
)


In [33]:
import json
results = []
paginator = s3_client.get_paginator('list_objects_v2')
response_iterator = paginator.paginate(
    Bucket='meshkorea-fulfillment-data',
    Prefix='sample_data_matnet_input/'
)
count=0
for page in response_iterator:
    for content in page['Contents']:
        if os.path.exists(content['Key']):
            continue
        if '전체' in content['Key']:
            continue
        try:
            s3_client.download_file('meshkorea-fulfillment-data', content['Key'], content['Key'])
            if count%100==0:
                print(content['Key'])
            count+=1
        except Exception as e:
            print(e)
            print(content)

sample_data_matnet_input/samples/2022-04-01하남센터2회차agent:101600.json
sample_data_matnet_input/samples/2022-04-02김포센터2회차agent:71996.json
sample_data_matnet_input/samples/2022-04-02하남센터1회차agent:92723.json
sample_data_matnet_input/samples/2022-04-03김포센터1회차agent:57733.json
sample_data_matnet_input/samples/2022-04-03남양주센터1회차agent:82013.json
sample_data_matnet_input/samples/2022-04-03하남센터2회차agent:101597.json
sample_data_matnet_input/samples/2022-04-04김포센터2회차agent:71992.json
sample_data_matnet_input/samples/2022-04-04하남센터1회차agent:93713.json
sample_data_matnet_input/samples/2022-04-05김포센터1회차agent:73434.json
sample_data_matnet_input/samples/2022-04-05남양주센터2회차agent:71895.json
sample_data_matnet_input/samples/2022-04-06곤지암센터(헬로)2회차agent:84178.json
sample_data_matnet_input/samples/2022-04-06김포센터2회차agent:97825.json
sample_data_matnet_input/samples/2022-04-06하남센터1회차agent:94863.json
sample_data_matnet_input/samples/2022-04-07김포센터1회차agent:73444.json
sample_data_matnet_input/samples/2022-04-07하남센터1회차age

In [34]:
import os
import orjson
nodes = []
for i in os.listdir('./sample_data_matnet_input/samples'):
    if i.startswith('.'):
        continue
    with open('./sample_data_matnet_input/samples/'+i) as f:
        tmp = np.array(orjson.loads(f.read())['durations'])
    if (tmp>1e4).sum()!=0:
        print(1)
        os.remove('./sample_data_matnet_input/samples/'+i)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [20]:
tmp[0]

array([0.00000000e+00, 1.21931774e+03, 9.04833563e+02, 1.21780992e+03,
       4.32724252e+06, 1.21470730e+03, 1.27991778e+03, 1.39996941e+03,
       1.61884723e+03, 1.41515417e+03, 1.48980875e+03, 1.27834718e+03,
       6.44622825e+02, 1.48294422e+03, 1.46728987e+03, 1.59340660e+03,
       1.28106788e+03, 1.59340660e+03, 9.36864807e+02, 8.19142897e+02,
       1.60183035e+03, 1.23719469e+03, 1.48769528e+03, 9.68018244e+02,
       1.48980875e+03, 1.30684795e+03, 1.35801773e+03, 1.35620567e+03,
       1.05951615e+03, 1.23768969e+03, 1.27513720e+03, 1.28106788e+03,
       1.28038301e+03, 1.22397840e+03, 1.27991778e+03])

In [12]:
np.array(nodes).max(axis=0)

array([ 986881.66391917, 1976116.0223603 ])

In [17]:
np.array(nodes).max(axis=0)/np.array(nodes)

array([[1.04788274, 1.0133487 ],
       [1.04709381, 1.01366369],
       [1.04703417, 1.01288283],
       ...,
       [1.0428771 , 1.01079033],
       [1.04827181, 1.00957359],
       [1.04325278, 1.0107476 ]])

In [39]:
np.random.permutation(os.listdir('./sample_data_matnet_input/samples'))

array(['2022-05-30김포센터1회차agent:72020.json',
       '2022-05-11김포센터2회차agent:71988.json',
       '2022-04-08하남센터2회차agent:101589.json', ...,
       '2022-05-22남양주센터1회차agent:56307.json',
       '2022-05-22남양주센터3회차agent:82547.json',
       '2022-03-19남양주센터1회차agent:56304.json'], dtype='<U39')